var productsArray = {
    cleansers: {
        detail: {
            heading: "Skin Cleansers",
            qt: "513 Results",
            page_desc: "Keep your skin clean and refreshed with our extensive range of skin cleansers. We have a thorough choice of cleansers, micellar waters and make-up removers designed to cater for each individual skin type and concern, from a wide range of brands. Whether you suffer from sensitive, oily or acne prone skin, you can achieve the results you require from our tailored choices. For a professional cleanse, try our range of premium brands such as Caudalie, Avene and Decleor. For a more medicated, specialized cleanse, why not check out SkinCeuticals, Murad or Paula's Choice? Remove dirt, grime and impurities effectively by ensuring one of our cleansers is incorporated into your daily skin care regime." 
        },
        arr : [
            {
                id: "cl1",
                main_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11535230-2295043599450781.jpg",
                hover_img: "https://static.thcdn.com/images/small/webp//productimg/original/11535230-8544892768833011.jpg",
                title: "SkinCeuticals Gentle Cleanser 6.8 fl. oz",
                bPrice: "38.00",
                aPrice: "36.00",
                desc: "Experience a mild yet effective cleanse with SkinCeuticals Gentle Cleanser, a non-foaming face wash that performs a delicate cleanse while conditioning the skin. Suitable for daily use, and for sensitive skin, the gentle, creamy formula has been developed with an emollient-rich surfactant system, and contains a 3% concentration comprising Allantoin, Glycerin and Orange Oil that nourishes and resurfaces skin to leave it feeling soft and supple. Deeply moisturizing, the face wash expertly lifts away dirt and makeup, including long-wearing products, while replenishing and priming skin ready for the next steps in your skincare regimen. After use, skin feels clean, fresh and comfortable with renewed softness. Suitable for dry, normal, sensitive, reactive, or post-procedure skin. Non-comedogenic. Free from parabens, sulfates, soap, synthetic-fragrance, dye and alcohol.",
                ingredients: "Aqua / Water / Eau, C12-15 Alkyl Benzoate, Glycerin, Propanediol, Cetyl Alcohol, Methyl Gluceth-20, Neopentyl Glycol Dicaprate, Peg-100 Stearate, Glyceryl Stearate, Polyglyceryl-4 Caprate, Phenoxyethanol, Citrus Aurantium Dulcis Oil / Orange Peel Oil, Limonene, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Capryl/Capramidopropyl Betaine, Caprylyl Glycol, Polysorbate 20, Allantoin, Sodium Hydroxide, Pentaerythrityl Tetra-Di-T-Butyl Hydroxyhydrocinnamate, Disodium Edta, Polyquaternium-39, Sodium Chloride, Peg-30 Dipolyhydroxystearate, Trideceth-6, Glycolic Acid, Sodium Benzoate.",
                procedure: ["Twice daily, apply a small amount to a wet face and neck with light circular motion.", "Rinse thoroughly with water."],
                reviews: 5,
                gender: "men",
                type: "oily"
            },
            {
                id: "cl2",
                main_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11370307-1475014852189893.jpg",
                hover_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11370307-3954944342301413.jpg",
                title: "EltaMD Foaming Facial Cleanser 207ml",
                bPrice: "32.00",
                aPrice: "27.20",
                desc: "Elta MD Foaming Facial Cleanser is an innovative formula with a bromelain and apple amino acid blend. Its self-foaming action gently yet thoroughly removes makeup, oil and other impurities. Now patients with even the most sensitive skin can experience deep-pore cleansing without drying or irritating their skin. Suited for all skin types. <b>Who is this for?</b><br>Ideal for those who want an oil-free cleanser. Suitable for all skin types.",
                ingredients: " <b>Key Ingredients:</b><br>Bromelain: Enzymes found in pineapples that work as an anti-inflammatory and reduces inflammation. Adds the foaming feature, leaving skin silky smooth.<br> <b>Full Ingredients:</b><br/>Purified Water, Sodium Cocoyl Glycinate, Acrylates Copolymer, Sodium Cocoyl Apple Amino Acids, Methyl Perfluoroisobutyl Ether, Magnesium Silicate, Methyl Perfluorobutyl Ether, Bromelain, Dimethicone Copolyol, Polyhydroxystearic Acid, Isononyl Isononanoate, Ethylhexyl Isononanoate, Sodium Cocamidopropyl PG-Dimonium Chloride Phosphate, Phenoxyethanol, Sodium Hydroxide, Capryloyl Glycine, Undecylenoyl Glycine, Sodium Bisulfite, Fragrance.",
                procedure: ["On damp skin, gently massage in circular motion. Allow 30 seconds for cleanser to foam. Rinse thoroughly."],
                reviews: 3,
                gender: "women",
                type: "dry"
            },
            {
                id: "cl3",
                main_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11165912-1924943596087530.jpg",
                hover_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11165912-2004943596135047.jpg",
                title: "Sarah Chapman Skinesis Rapid Radiance Cleanse (100ml)",
                bPrice: "70.00",
                aPrice: "69.00",
                desc: "The Sarah Chapman Skinesis Rapid Radiance Cleanse is an indulgent creamy cleanser, that doubles as a 2-minute detoxifying mask due to its blend of rare clays. The multi-functioning, radiance-boosting treatment is powered by lactic and salicylic acids. The exfoliating formula helps to buff away dead skin cells, while French red clay, PoreAway and Detoxophane complexes seek to decongest, for a clarified, refined texture. Fortified with vitamin C, the cooling cleanser encourages a complexion that appears brighter with enhanced radiance, alongside a cocktail of vitamin oils nourishing the visage and melting away impurities.",
                ingredients: "Aqua (Water), Glycerin, Prunus Amygdalus Dulcis (Sweet Almond) Oil, Decyl Glucoside, Carthamus Tinctorius (Safflower) Seed Oil, Stearic Acid, Glyceryl Stearate SE, Pentaclethra Macroloba Seed Oil, Butyrospermum Parkii (Shea) Butter, Glycol Stearate, Kaolin, Cocamidopropyl Betaine, Illite, Cetearyl Alcohol, Betaine, Magnesium Aluminium Silicate, Phenoxyethanol, Lepidium Sativum Sprout Extract, Citrus Bergamia Fruit Oil, Salicylic Acid, Limonene, Sodium Ascorbyl Phosphate, Xanthan Gum, Linalool, Lactic Acid, Benzyl Alcohol, Sodium Hydroxide, Citrus Aurantium Amara Leaf/Twig Oil, Alcohol, Cyclodextrin, Calendula Officinalis Flower Extract, Ethylhexylglycerin, Menthol, Lecithin, Disodium EDTA, Sodium Benzoate, Menthyl Lactate, Geraniol, Dehydroacetic Acid, Pistacia Lentiscus (Mastic) Gum, Pelargonium Graveolens Oil, Citral, Potassium Sorbate, Citronellol, Citric Acid, Citrus Aurantium Amara Flower Oil.",
                procedure: ["<i class='fa-regular fa-sun'></i> AM / <i class='fa-regular fa-moon'></i> PM", "When to Use: ​The first step in your routine.", "Recommended Amount:​ 2-4 pumps.", "Application:​ Massage onto a dry face and neck and rinse. For use as a mask, leave on for 2 minutes and rinse.", "Routine: Follow with serums, moisturiser and SPF."],
                reviews: 4,
                gender: "boys",
                type: "combination"
            },
            {
                id: "cl4",
                main_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11289657-9384876690289403.jpg",
                hover_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11289657-1754876690336179.jpg",
                title: "SkinMedica AHA/BHA Exfoliating Cleanser (6oz)",
                bPrice: "50.00",
                aPrice: "48.00",
                desc: "This exfoliating cleanser gently scrubs away dead skin using ultra-fine Jojoba Beads with Alpha-Hydroxy and Beta-Hydroxy Acids to improve the appearance of skin tone and texture.<br/><b>Benefits:</b><br><ul><li>Thoroughly removes environmental pollutants, excess oil and makeup.</li><li>Hydrates and refreshes skin.</li><li>Can be used by all skin types</li></ul>",
                ingredients: "Water/Aqua/Eau, Sodium C14-16 Olefin Sulfonate, Cocamidopropyl Betaine, PEG/PPG-8/3 Diisostearate, Hydrogenated Jojoba Oil, Acrylates Copolymer, Vaccinium Myrtillus Fruit/Leaf Extract, Saccharum Officinarum Extract, Acer Saccharum Extract, Citrus Aurantium Dulcis Fruit Extract, Citrus Limon Fruit Extract, Salicylic Acid, Glycyrrhiza Glabra Root Extract, Panthenol, Bisabolol, Citric Acid, Glycerin, Ethylhexylglycerin, Sodium Hydroxide, Disodium EDTA, Potassium Sorbate, Phenoxyethanol, Lavandula Angustifolia Oil, Citrus Aurantium Dulcis Peel Oil, Mica, Tin Oxide, Titanium Dioxide (CI 77891).",
                procedure: ["Moisten skin with warm water.", "Apply a small amount to the fingertips, add a little water and gently exfoliate and cleanse the face using small circular motions.", "Rinse thoroughly with warm water.", "Use as often as needed. Avoid getting in eyes. If contact occurs, rinse eyes thoroughly with water."],
                reviews: 5,
                gender: "women",
                type: "normal"
            },
            {
                id: "cl5",
                main_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11054487-7024901860582746.jpg",
                hover_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11054487-8284935531346776.jpg",
                title: "First Aid Beauty Face Cleanser (5 oz.)",
                bPrice: "24.00",
                aPrice: "22.00",
                desc: "First Aid Beauty Face Cleanser gently cleanses the skin, removes surface oils, makeup, dirt and grime. Its whipped texture transforms into a rich cream when blended with water. This cleanser is infused with a powerful botanical antioxidant blend that works hard to scavenger free radicals.</br><b>Benefits:</b><br><ul><li>Preserves the natural oils that protect the skin.</li><li>Calms any redness or irritations.</li><li>Formula is free of parabens, harsh chemicals and colorants.</li><li>Recommended for sensitive or irritated skin.</li></ul>",
                ingredients: "Water (Aqua), SodiumCocoyl Isethionate, Glycerin, Stearic Acid, Aloe Barbadensis Leaf Juice, Stearyl Alcohol,Sodium PCA, Camellia Sinensis Leaf Extract, Chrysanthemum Parthenium (Feverfew) Extract, Glycyrrhiza Glabra (Licorice) Root Extract, Allantoin, Hydroxypropyl Methylcellulose, Disodium Cocoamphodiacetate,Coco Glucoside, Glyceryl Stearate, Disodium EDTA, Caprylyl Glycol, Phenoxyethanol.",
                procedure: ["Dampen the face and dispense a dime-sized portion of cleanser onto fingertips.", "Delicately massage into all zones of the face.", "Remove with a softwash cloth or a splash of water.", "Recommended for daily use in the am and pm."],
                reviews: 5,
                gender: "men",
                type: "combination"
            },
            {
                id: "cl6",
                main_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/10363611-1624963531670292.jpg",
                hover_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/10363611-1664963531714518.jpg",
                title: "Eve Lom Cleanser 7oz (Worth $170)",
                bPrice: "135.00",
                aPrice: "134.00",
                desc: "The Eve Lom Cleanser was described by Vogue as \"probably the best cleanser in the world\" and is the foundation of the Eve Lom skincare regimen. With the cleanser's signature blend of four aromatic plant oils, specially woven 100% cotton Muslin Cloth and quick routine, the result is incredibly glowing, radiant skin with a smoother, more refined texture. The difference can be seen instantly and just keeps on improving with use.<br><b>Benifits:</b><br><ul><li>Deep cleans without drying or stripping the skin.</li><li>Removes even the most stubborn waterproof makeup.</li><li>Can be used by all skin types.</li><li>Exfoliates, tones and improves circulation.</li><li>Softens and conditions skin.</li></ul>",
                ingredients: "Paraffinum Liquidum (Mineral Oil), Peg-30 Lanolin, Cetearyl Alcohol, Bis-Diglyceryl Polyacyladipate-2, Aluminum Stearate, Theobroma Cacao (Cocoa) Seed Butter, Peg-75 Lanolin, Eugenia Caryophyllus (Clove) Leaf Oil, Humulus Lupulus (Hops) Oil, Chamomilla Recutita (Matricaria) Flower Oil, Eucalyptus Globulus Leaf Oil, BHT.",
                procedure: ["Use once a day, at night for normal/dry skin types.", "Use twice a day, morning and night for congested skins.", "Massage a small amount onto the face and neck onto dry skin over the grime and makeup from the day.", "Fill the basin with hot water and immerse the Muslin Cloth.", "Squeeze off excess water and hold the cloth over the face and neck for a few seconds while taking a deep breath.", "The heat will soften the skin and open the pores allowing the aromatic oils to cleanse the skin of impurities.", "For optimum results repeat this stage three times.", "Fold the hot, rinsed cloth into a square and work it in small circular movements across the face and neck to remove all traces of Cleanser and makeup.", "Finally rinse the cloth in cool water and hold over the face and neck."],
                reviews: 5,
                gender: "men",
                type: "normal"
            },
            {
                id: "cl8",
                main_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11207443-2214866130380732.jpg",
                hover_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11207443-7744859308052472.jpg",
                title: "DHC Deep Cleansing Oil (Various Sizes)",
                bPrice: "15.00",
                aPrice: "14.00",
                desc: "Experience the ultimate cleanse with DHC's Deep Cleansing Oil, a revolutionary oil makeup remover infused with antioxidant-rich Olive Oil.<br>Performing a deep clean on skin, the vitamin-rich cleanser glides effortlessly across the face and transforms into a milky, comforting emulsion upon contact with water. Its water-soluble formula rinses clean effortlessly, and effectively lifts away makeup and impurities. Skin is left feeling nourished and hydrated with a radiant glow. Expect refreshed, younger looking skin.<br>In a clinical study, 92% of participants agreed Deep Cleansing Oil worked better than a leading cleanser at removing complexion makeup.",
                ingredients: "Olea Europaea (Olive) Fruit Oil, Caprylic/Capric Triglyceride, Sorbeth-30 Tetraoleate, Pentylene Glycol, Phenoxyethanol, Tocopherol, Stearyl Glycyrrhetinate, Rosmarinus Officinalis (Rosemary) Leaf Oil.",
                procedure: ["Dispense into dry hands, then massage onto dry face to dissolve make-up, dirt and other impurities. Rinse thoroughly."],
                reviews: 4,
                gender: "men",
                type: "normal"
            },
            {
                id: "cl9",
                main_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/12100152-5864924700785761.jpg",
                hover_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/12100152-1484864616906646.jpg",
                title: "The Organic Pharmacy Rose Facial Cleansing Gel 100ml",
                bPrice: "85.00",
                aPrice: "84.00",
                desc: "Hydrate skin and eliminate impurities with our organic Rose Facial Cleansing Gel. This fragrant, Aloe-based wash is infused with Calendula to soothe redness and cleanse without drying. Rose Hip protects and conditions for fresh, glowing skin.",
                ingredients: "Aloe Barbadensis Leaf Juice, Aqua (Water) , Glycerin, Cocoamidopropyl Betaine, Sodium Olivamphoacetate, Alcohol, Panthenol , Rosa Canina Fruit Oil, Sodium Chloride, Citrus Grandis (Grapefruit) Seed Extract, Pelargonium Graveolens Oil , Parfum (Fragrance), Chondrus Crispus Extract, Algin, Xanthan Gum, Chondrus Crispus Powder, Calcium Ascorbate, Vaccinium Myrtillus Fruit Extract, Calendula Officinalis Extract, Ascorbic Acid, Helianthus Annuus (Sunflower) Seed Oil, Tocopherol, Citronellol, Geraniol, Linalool.",
                procedure: ["Mix a small amount with water, massage over face and neck and rinse off.", "For best results, remove with a muslin cloth soaked in hand-hot water. Avoid contact with eyes."],
                reviews: 3,
                gender: "women",
                type: "normal"
            },
            {
                id: "cl10",
                main_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/10364095-1175048093463228.jpg",
                hover_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/10364095-1354864282818603.jpg",
                title: "Dermalogica Special Cleansing Gel (500ml, Worth $78)",
                bPrice: "68.00",
                aPrice: "65.00",
                desc: "Dermalogica Special Cleansing Gel foams away impurities without leaving your skin feeling tight or dry. Anti-inflammatory balm mint and lavender extracts soothe your skin, while natural quillaja saponaria gently foams away toxins and cleanses debris.<br>Fragrance and soap free, Dermalogica Special Cleansing Gel is ideal for combination to normal skin. Designed to thoroughly remove impurities without disturbing the skin's natural moisture balance, this cleanser will leave your skin feeling cool and calm.",
                ingredients: "Water/Aqua/Eau, Disodium Laureth Sulfosuccinate, Sodium Lauroyl Sarcosinate, Quillaja Saponaria Bark Extract Lavandula Angustifolia (Lavender) Oil, Melissa Officinalis Leaf Extract, Citrus Limon (Lemon) Peel Oil, Citrus Aurantium Bergamia (Bergamot) Fruit Oil, Cymbopogon Winterianus Herb Oil, Glycerin, Cocamidopropyl Betaine, Coco-Betaine, Hydroxyethylcellulose, Sodium Cocoyl Isethionate, Capryloyl Glycine, Sodium Lauryl Sulfoacetate, Methylpropanediol, Ethylhexylglycerin, Caprylhydroxamic Acid, PPG-5-Ceteth-20, Sodium Hydroxide, Disodium EDTA.",
                procedure: ["Pump a small amount of cleanser into the palm of your hand.", "Gently work the gel into a deep cleansing lather and apply to your dampened face and throat.", "Rinse with warm water and repeat for professional cleansing results.", "For best results follow with Dermalogica Multi-Active Toner and prescribed Dermalogica Moisturiser."],
                reviews: 4,
                gender: "men",
                type: "normal"
            },
            {
                id: "cl11",
                main_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11291539-1905002181556714.jpg",
                hover_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11291539-1594855672799181.jpg",
                title: "Obagi Medical Nu-Derm Foaming Gel",
                bPrice: "44.00",
                aPrice: "43.00",
                desc: "Your Transformation begins with a soap-free cleanser that gently removes impurities, oil and makeup to leave skin clean, fresh and ready for the next step.",
                ingredients: "Purified Water, Sodium Lauroyl Oat Amino Acids, Cocamidopropyl Betaine, Sodium Laureth Sulfate, Aloe Barbadensis Leaf Juice, Medicago Sativa (Alfalfa) Extract, Borago Officinalis Extract, Chamomilla Recutita (Matricaria) Extract, Sodium Chloride, Xanthan Gum, Saponins, Phenoxyethanol, Methylparaben, Ethylparaben, Butylparaben, Propyl-Paraben, Isobutylparaben, Fragrance, D&C Red No.33, Fd&C Yellow No.5.",
                procedure: ["Apply to wet face, rinse with lukewarm water and gently pat dry.", "Avoid rubbing the skin with a towel. For AM/PM use."],
                reviews: 5,
                gender: "men",
                type: "normal"
            },
            {
                id: "cl12",
                main_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11897434-6604882135119693.jpg",
                hover_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11897434-1624882135167429.jpg",
                title: "Sunday Riley Ceramic Slip Cleanser",
                bPrice: "53.00",
                aPrice: "35.00",
                desc: "Experience a purifying cleanse with the Sunday Riley Ceramic Slip Cleanser, a plant-based cleanser formulated with four plant-based soaps to leave skin feeling clean, hydrated and revitalized.<br>Eliminating dirt and impurities without stripping skin, the gentle face wash utilizes French Green Clay to draw out dirt, oil, pollution and makeup. It performs a deep cleanse on pores to decongest and refine their appearance. Suitable for all skin types, including sensitive, the foaming cleanser will gently yet effectively clean the skin while replenishing hydration. Its dose of Rice Oil Esters protect against dehydration. Skin is left feeling softer, balanced, healthier and radiant.",
                ingredients: "Water/Aqua/Eau, Disodium Laureth Sulfosuccinate, Octyldodecanol, Polyacrylate-33, Propanediol, Polyglyceryl-2 Caprate, Sodium Cocoyl Isethionate, Montmorillonite, Kaolin, Olive Oil Polyglyceryl-6 esters, Rice Oil Glycereth-8 esters, Phospholipids, Sodium Methyl Cocoyl Taurate, Sodium Lauroamphoacetate, Bisabolol, Pentylene Glycol, Sodium Chloride, Sodium Phytate, Caprylyl Glycol, Dehydroacetic Acid, Benzoic Acid, Propylene Carbonate, Linalool, Farnesol.",
                procedure: ["Massage into the skin to remove dirt, oil, pollution, and makeup.", "Rinse with warm water."],
                reviews: 5,
                gender: "women",
                type: "normal"
            },
            {
                id: "cl13",
                main_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11429053-8834884255296385.jpg",
                hover_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11429053-1934884255611169.jpg",
                title: "La Roche-Posay Toleriane Purifying Foaming Cream Facial Cleanser for Sensitive Skin with Glycerin, 4.22 Fl. Oz.",
                bPrice: "24.99",
                aPrice: "23.99",
                desc: "Experience a purifying cleanse with the Sunday Riley Ceramic Slip Cleanser, a plant-based cleanser formulated with four plant-based soaps to leave skin feeling clean, hydrated and revitalized.<br>Eliminating dirt and impurities without stripping skin, the gentle face wash utilizes French Green Clay to draw out dirt, oil, pollution and makeup. It performs a deep cleanse on pores to decongest and refine their appearance. Suitable for all skin types, including sensitive, the foaming cleanser will gently yet effectively clean the skin while replenishing hydration. Its dose of Rice Oil Esters protect against dehydration. Skin is left feeling softer, balanced, healthier and radiant.",
                ingredients: "Water, Glycerin, Potassium Myristate, Glyceryl Stearate SE, Potassium Stearate, Potassium Laurate, Potassium Palmitate, Coco-Glucoside, Tetrasodium EDTA",
                procedure: ["Work into a lather between palms with lukewarm water.", "Apply to the face using gentle massaging motion, avoiding the eye area.", "Rinse well and pat dry."],
                reviews: 5,
                gender: "women",
                type: "normal"
            },
            {
                id: "cl14",
                main_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11287446-8114871898290271.jpg",
                hover_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11287446-2064871898323625.jpg",
                title: "Epionce Lytic Gel Cleanser",
                bPrice: "40.00",
                aPrice: "35.00",
                desc: "The Epionce Lytic Gel Cleanser is a powerful treatment specifically developed for oily and combination skin types, working to eliminate the root causes of breakouts and instantly refresh.<br>The ultra-lightweight formula utilises an EpiK™ complex of natural extracts to unclog pores and remove makeup, with Willow Bark helping dissolve dead skin cells and regulate excess oil production without disrupting the natural lipid barrier.<br>Soothing Marshmallow and toning Menthol help promote a more even and balanced surface texture, optimizing skin for further treatments and enabling maximum absorption. Ideal for problematic skin prone to conditions such as acne, dermatitis and psoriasis, helping achieve a clarified and rejuvenated complexion. ",
                ingredients: "Water (Aqua), Sodium Cocoamphoacetate, Sodium Lauroyl Sarcosinate, Glycerin, Lauryl Glucoside, Sodium Cocoyl Glutamate, Sodium Lauryl Glucose Carboxylate, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Althaea Officinalis (Marsh Mallow) Root Extract, Butylene Glycol, Caprylyl Glycol, Citrus Aurantium Dulcis (Orange) Fruit Extract, Coco-Glucoside, Disodium EDTA, Ethylhexylglycerin, Glyceryl Oleate, Hexylene Glycol, Lavandula Angustifolia (Lavender) Flower Extract, Limonene, Linalool, Menthol, Phenoxyethanol, Phoenix Dactylifera (Date) Fruit Extract, Salix Alba (Willow) Bark Extract, Sodium Hydroxide.",
                procedure: ["Apply 1-2 pumps to damp skin.", "Rinse with warm water.", "Pat skin dry."],
                reviews: 4,
                gender: "men",
                type: "normal"
            },
            
    ]},
    moisturisers: {
        detail: {
            heading: "Moisturizers",
            qt: "1054 Results",
            page_desc: "SkinStore offers a complete range of moisturizers which cater for every individual skin type and concern. Moisturizing your skin morning and night is one of the most important steps within your skin care regime, and a product perfectly designed for you can make all the difference. Featuring professional skin care products from brands such as NUXE, Elizabeth Arden and Erno Laszlo, you'll be sure to find the right one to look after your skin. From moisturizers aimed to nourish and hydrate, to night creams designed to prevent the signs of aging and vitality, your skin will be on it's way to looking its healthiest."
        },
        arr : [
            {
                id: "mo1",
                main_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11289613-6975043613167717.jpg",
                hover_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11289613-3764892771164923.jpg",
                title: "SkinCeuticals Daily Moisture",
                bPrice: "80.00",
                aPrice: "76.00",
                desc: "Protect and hydrate skin with <b>SkinCeuticals Daily Moisture</b>, a lightweight moisturizer that provides long-lasting hydration while minimizing the appearance of pores.<br/>Melting effortlessly into skin with no greasy residue, it intensely hydrates and nourishes, delivering a combination of Vitamin E and nutrient-rich Algae extracts to soften and replenish, while seven botanical extracts help to reduce the look of enlarged pores. Restoring and maintaining moisture, it will intensely hydrate while protecting against environmental damage.<br/> <i>Suitable for normal to oily skin.</i><br/><b>**Winner! Best Skincare Brand and Best Longstanding Brand 2017 as voted for by SkinStore customers.**</b>",
                ingredients: "Aqua / Water / Eau, Glycerin, Cetyl Palmitate, Stearic Acid, Butylene Glycol, Palmitic Acid, Tocopherol, Dimethicone, Polymethylsilsesquioxane, Glyceryl Stearate, Sorbitol, Ci 77163 / Bismuth Oxychloride, Phenoxyethanol, Peg-100 Stearate, Sodium Hyaluronate, Hamamelis Virginiana Water / Witch Hazel Water, Peg-75 Stearate, Cetyl Alcohol, Carbomer, Ethylhexyl Hydroxystearate, Allantoin, Panthenol, Ceteth-20, Triethanolamine, Caprylyl Glycol, Xanthan Gum, Propylene Glycol, Steareth-20, Disodium Edta, Myristic Acid, Betaine, Chlorella Vulgaris Extract, Laminaria Saccharina Extract, Glucose, Chamomilla Recutita Flower Extract / Matricaria Flower Extract, Zingiber Officinale Root Extract / Ginger Root Extract, Sanguisorba Officinalis Root Extract, Cinnamomum Cassia Bark Extract, Thymus Vulgaris Flower/Leaf Extract - Thyme Flower/Leaf Extract, Retinyl Palmitate, Helianthus Annuus Seed Oil / Sunflower Seed Oil, Sodium Benzoate, Zinc Sulfate, Laminaria Ochroleuca Extract, Glycyrrhiza Glabra Extract / Licorice Root Extract, Urtica Dioica Extract / Nettle Extract, Equisetum Arvense Extract, Betula Alba Leaf Extract, Citric Acid, Potassium Sorbate, Cinnamal, Pyridoxine Hcl.",
                procedure: ["Once or twice daily, apply a dime size of the moisturizer to the face, neck, and chest."],
                reviews: 3,
                gender: "women",
                type: "oily"
            },
            {
                id: "mo2",
                main_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11647081-4134943595225699.jpg",
                hover_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11647081-1414943595280470.jpg",
                title: "Sarah Chapman Icon Night Smartsome A3 X503 Moisturiser 30ml",
                bPrice: "157.00",
                aPrice: "156.00",
                desc: "Combat the appearance of ageing with Sarah Chapman Icon Night Smartsome A3 X503 Moisturiser, a lightweight and velvety night cream formulated with advanced scientific technologies.<br>Housed in an easy-to-use pump bottle, the moisturiser uses Ecoskin® probiotics, Smartsome™ actives and vitamin-rich IconA® to form a protective barrier against environmental toxins and free radicals, and stimulate cell renewal for a transformed skin texture.<br>The cream helps to smooth out fine lines and wrinkles, minimise the appearance of dark spots and discolouration, and improve skin density. A nourishing blend of Jasmine, Hyacinth and Rose Essential Oils works to restore luminosity and repair damaged skin, creating a complexion which is radiant, revitalised and visibly youthful.",
                ingredients: "Aqua (Water), Caprylic/Capric Triglyceride, Cyclopentasiloxane, Cetyl Alcohol, Glyceryl Stearate, Alpha-Glucan Oligosaccharide, Limnanthes Alba (Meadowfoam) Seed Oil, Butylene Glycol, C12-15 Alkyl Benzoate, Glycerin, Ribose, Retinal, Polymnia Sonchifolia Root Juice, Adansonia Digitata, Hydrolyzed Verbascum Thapsus Flower, Passiflora Edulis Seed Oil, Hydrolyzed Pepper Fruit Extract, Myristoyl Tripeptide-31, Palmitoyl Hexapeptide-12, Palmitoyl Hexapeptide-52, Palmitoyl Tetrapeptide-50, Heptapeptide-15 Palmitate, Palmitoyl Heptapeptide-18, Copper Palmitoyl Heptapeptide-14, Butyrospermum Parkii (Shea) Butter, Retinyl Palmitate, Ceramide Ng, Bisabolol, Allantoin, Peg-10 Rapeseed Sterol, Rubus Chamaemorus Seed Oil, Helianthus Annuus (Sunflower) Seed Oil, Lactobacillus, Lactic Acid/Glycolic Acid Copolymer, Cedrus Atlantica Bark Oil, Jasminum Officinale (Jasmine) Flower Extract, Pelargonium Graveolens Flower Oil, Santalum Spicata Wood Oil, Rosa Damascena Flower Oil, Lonicera Japonica (Honeysuckle) Flower Extract, Lonicera Caprifolium, Caprylyl Glycol, Acrylamide/Sodium Acryloyldimethyltaurate Copolymer, Cyclodextrin, Tribehenin, Pentylene Glycol, Xanthan Gum, Polyvinyl Alcohol, Maltodextrin, Steareth-20, Ceteth-20, Isohexadecane, Peg-75 Stearate, Polysorbate 80, Ammonium Acryloyldimethyltaurate/Vp Copolymer, Ethylhexylglycerin, Sodium Gluconate, Phenoxyethanol, Parfum (Fragrance), Citric Acid, Sorbitan Oleate, T-Butyl Alcohol, Sodium Benzoate, Potassium Sorbate, Glyceryl Caprylate, Phenylpropanol, Tocopherol, Benzyl Benzoate, Citronellol, Farnesol, Geraniol, Linalool.",
                procedure: ["Smooth over Icon night cream over the neck, face and chest to target all signs of ageing.", "Avoid contact with the eyes, if discomfort occurs then rinse with warm water.", "For external use only."],
                reviews: 1,
                gender: "men",
                type: "oily"
            },
            {
                id: "mo3",
                main_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11054488-6294867924186974.jpg",
                hover_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11054488-4844981948470726.jpg",
                title: "First Aid Beauty Ultra Repair Cream (6 oz.)",
                bPrice: "38.00",
                aPrice: "37.00",
                desc: "FAB Ultra Repair Cream is a thick, rich, emollient product that hydrates deep down with exceptional penetration. With the help of Colloidal Oatmeal, Shea Butter, soothing Eucalyptus Oil and ceramides, FAB Ultra Repair Cream provides immediate relief and visible improvement for distressed skin. FAB Antioxidant Booster is there to defend skin from free radical damage. Ultra Repair Cream can be used all over the body and on the face.",
                ingredients: "Colloidal Oatmeal, Water, Stearic Acid, Glycerin, C12-15 Alkyl Benzoate, Caprylic/Capric Triglyceride, Glyceryl Stearate, Glyceryl Stearate SE, Cetearyl Alcohol, Caprylyl Glycol, Phenoxyethanol, Butyrospermum Parkii (Shea Butter), Squalane, Allantoin, Sodium Hydroxide, Dimethicone, Xanthum Gum, Disodium EDTA, Chrysanthemum Parthenium (Feverfew) Extract, Camellia Sinensis Leaf Extract, Butylene Glycol, Glycyrrhiza Glabra (Licorice) Root Extract, Eucalyptus Globulus, Ceramide 3.",
                procedure: ["Apply as needed."],
                reviews: 4,
                gender: "women",
                type: "oily"
            },
            {
                id: "mo4",
                main_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11290635-9025043619566462.jpg",
                hover_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11290635-9174978287699645.jpg",
                title: "SkinCeuticals Triple Lipid Restore 2:4:2",
                bPrice: "150.00",
                aPrice: "145.00",
                desc: "Treat your skin to the smoothing properties of SkinCeuticals Triple Lipid Restore 2:4:2, an anti-aging cream that improves the texture of skin while directly addressing age-related lipid loss.<br>Working to nourish and visibly improve the appearance of skin, the moisturizer is formulated with a concentration of lipids (2% pure ceramides, 4% natural cholesterol and 2% fatty acids) easily utilized by skin, and fortified with the first and patented 2:4:2 cholesterol-dominant ratio to help restore skin's barrier while supporting natural self-repair. Lightweight and fast-absorbing, the cream melts effortlessly into skin, effectively improving texture, fullness and the appearance of pores. Expect a brighter, more even-looking canvas that feels smooth, comforted and youthful. Enriched with an essential oil blend of Lavender, Rosemary, and Peppermint Oil for a cooling, comforting effect.",
                ingredients: "Aqua/Water/Eau, Dimethicone, Hydrogenated Polyisobutene, Glycerin, Cholesterol, C12-15 Alkyl Benzoate, Ceramide 3, Helianthus Annuus Seed Oil Unsaponifiables/Sunflower Seed Oil Unsaponifiables, Bis-Peg-18 Methyl Ether Dimethyl Silane, Sodium Polyacrylate, Peg-10 Dimethicone, Nylon-12, Lauryl Peg-9 Polydimethylsiloxyethyl Dimethicone, Dimethicone/Peg-10/15 Crosspolymer, Phenoxyethanol, Disteardimonium Hectorite, Hydroxyethylpiperazine Ethane Sulfonic Acid, Ammonium Polyacryloyldimethyl Taurate, Chlorphenesin, Caprylyl Glycol, Peg/Ppg-18/18 Dimethicone, Propylene Carbonate, Disodium Edta, Acrylonitrile/Methyl Methacrylate/Vinylidene Chloride Copolymer, Adenosine, Dipropylene Glycol, Lavandula Angustifolia Oil/Lavender Oil, Rosmarinus Officinalis Leaf Oil/Rosemary Leaf Oil, T-Butyl Alcohol, Mentha Piperita Oil/Peppermint Oil, Sodium Citrate, Linalool, Isobutane, Ceramide Eop, Bht, Tocopherol, Limonene, D182888/1.",
                procedure: ["Apply a small amount between fingertips, warm and melt the cream in circular motions.", "Apply twice daily to face, neck and chest.", "Once open; it's most effective when used within 12 months."],
                reviews: 5,
                gender: "women",
                type: "oily"
            },
            {
                id: "mo5",
                main_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11218590-1294969854284175.jpg",
                hover_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11218590-1114969854216651.jpg",
                title: "Revive Moisturizing Renewal Cream 50ml",
                bPrice: "195.00",
                aPrice: "180.00",
                desc: "ts unique formula works overtime as you sleep to help eradicate imperfections and visibly diminish fine lines. Wake up to fresher, more beautiful skin. Provides overall glow for a luminous, youthful complexion. Featuring Glycolic Acid, this powerful perfecting night cream gently exfoliates, retexturizes, renews and moisturizes facial skin",
                ingredients: "Aqua (Water, Eau), Diisopropyl Dimer Dilinoleate, Dicaprylyl Maleate, Glycolic Acid, Cyclopentasiloxane, Glycerin, Helianthus Annuus (Sunflower) Seed Oil, Glyceryl Stearate, Butylene Glycol, Cetyl Alcohol, Cetyl Phosphate, Sodium Hydroxide, Isostearic Acid, Squalane, Sclerotium Gum, Oligopeptide-24, Ascorbyl Palmitate, Tocopheryl Acetate, Glycolipids, Sodium Hyaluronate, Tocopherol, Bisabolol, Allantoin, Sodium Pca, Butyrospermum Parkii (Shea) Butter, Caprylyl Glycol, Persea Gratissima (Avocado) Oil, Dimethicone, Phytosterols, Olea Europaea (Olive) Fruit Oil, Sodium Carbonate, Glycine Soja (Soybean) Oil, Sodium Oleate, Hydrogenated Lecithin, Myristic Acid, Citrus Aurantium Dulcis (Orange) Peel Oil, Sorbitan Oleate, Palmitic Acid, Stearic Acid, Phenoxyethanol, Disodium Edta, Limonene, Linalool",
                procedure: ["Apply nightly after cleanser, toner, and serum."],
                reviews: 5,
                gender: "men",
                type: "oily"
            },
            {
                id: "mo6",
                main_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11370304-7405014852016604.jpg",
                hover_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11370304-1194876993654206.jpg",
                title: "EltaMD AM Therapy Facial Moisturizer",
                bPrice: "41.00",
                aPrice: "30.00",
                desc: "Elta MD AM Therapy Facial Moisturizer provides all-day moisturizing in a very lightweight, oil-free moisturizer base. Elta MD AM Therapy Facial Moisturizer increases moisture absorption and retention by stimulating aquaporins in skin cells.",
                ingredients: "Purified Water, Cyclopentasiloxane, Ethylhexyl Isononanoate, Niacinamide, Lauryl PEG-9 Polymethylsiloxyethyl Dimethicone, Salix Alba (Willow) Bark Extract, Piptadenia Colubrina Peel Extract, Sodium Hyaluronate, Glycerin, Dimethicone, Allantoin, Caffeine, Ascorbyl Palmitate, Dimethicone/PEG-10/15 Crosspolymer, Sodium Chloride, Butylene Glycol, Phenoxyethanol, Capryloyl Glycine, Undecylenoyl Glycine, Disodium EDTA, Sodium Hydroxide.",
                procedure: ["Apply in the morning to cleansed skin."],
                reviews: 5,
                gender: "men",
                type: "oily"
            },
            {
                id: "mo7",
                main_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11370303-1255014851959274.jpg",
                hover_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11370303-1514871771637066.jpg",
                title: "EltaMD UV Clear Broad-Spectrum SPF46",
                bPrice: "41.00",
                aPrice: "40.00",
                desc: "With EltaMD UV Clear Broad-Spectrum SPF 46, you need not worry about your sensitive skin anymore. As the 2010 Winner of Elle Genius Award for Skin, EltaMD UV Clear Broad-Spectrum SPF 46 offers not only UVA/UVB protection, but also treatment for skin discoloration and acne. Its oil-free, light texture goes on smooth, leaving behind no residue on the skin. This product maintains skin health by freeing skin of fatty acid levels and reducing redness. This oil-free, non-comedogenic formula can be worn with or without makeup.",
                ingredients: "Inactive Ingredients: Purified Water, Cyclopentasiloxane, Niacinamide, Octyldodecyl Neopentanoate, Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Polyisobutene, PEG-7 Trimethylolpropane Coconut Ether, Sodium Hyaluronate, Tocopheryl Acetate, Lactic Acid, Oleth-3 Phosphate, Phenoxyethanol, Butylene Glycol, Iodopropynyl Butylcarbamate, Triethoxycaprylylsilane.",
                procedure: ["Apply liberally to face and neck 15 minutes before sun exposure.", "Use a water-resistant sunscreen if swimming or sweating.", "Re-apply at least every 2 hours."],
                reviews: 3,
                gender: "men",
                type: "oily"
            },
            {
                id: "mo8",
                main_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11291563-5235043619658436.jpg",
                hover_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11291563-1934892768127813.jpg",
                title: "SkinCeuticals Epidermal Repair",
                bPrice: "56.00",
                aPrice: "55.00",
                desc: "Epidermal Repair is specifically formulated for skin compromised by cosmetic procedures ranging from microdermabrasion to laser resurfacing, as well as skin sensitized by retinoid therapy or harsh environmental aggressors. This therapeutic treatment combines Beta Glucan and Centella Asiatica to provide a protective veil for traumatized skin while facilitating the biological processes necessary to accelerate restoration of the skin’s barrier. Epidermal Repair is clinically shown to greatly diminish redness and soothe irritated skin while the cosmetically elegant texture encourages daily use, especially during the critical healing period following rejuvenating procedures.",
                ingredients: "Aqua / Water / Eau, Dimethicone, Glycerin, Ethylhexyl Palmitate, Butylene Glycol, Cetyl Peg/Ppg-10/1 Dimethicone, Pentaerythrityl Tetraethylhexanoate, C30-45 Alkyl Dimethicone, Isohexadecane, Dipropylene Glycol, Peg/Ppg-18/18 Dimethicone, Magnesium Sulfate, Phenoxyethanol, Caprylyl Glycol, Dimethiconol, Sodium Palmitoyl Proline, Sodium Benzoate, Centella Asiatica Extract, Sodium Carboxymethyl Beta-Glucan, Citric Acid, Nymphaea Alba Extract / Nymphaea Alba Flower Extract.",
                procedure: ["Once daily, or as needed, massage a small amount evenly into affected area."],
                reviews: 5,
                gender: "men",
                type: "oily"
            },
            {
                id: "mo9",
                main_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11289681-1484871019698619.jpg",
                hover_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11289681-1904871019505803.jpg",
                title: "SkinMedica TNS Ceramide Treatment Cream (2oz)",
                bPrice: "72.00",
                aPrice: "65.00",
                desc: "This Ceramide-rich treatment cream with NouriCel-MD® works to rapidly restore skin's moisture while soothing and hydrating post-procedure, dry and compromised skin.",
                ingredients: "Purified Water, Cetyl Ethylhexanoate, Cetearyl Alcohol, Hydroxypropyl Bispalmitamide MEA (Ceramide), Human Fibroblast Conditioned Media, Dimethicone, Olea Europaea (Olive) Fruit Oil, Glycine Soja (Soybean) Oil, Cetearyl Glucoside, Palmitoyl Oligopeptide, Palmitoyl Tetrapepide-7, Tetrahexyldecyl Ascorbate, Avena Sativa (Oat) Kernel Extract, Glycine Soja (Soybean) Sterols, Retinyl Palmitate, Tocopheryl Acetate, Sodium Carboxymethyl Beta-Glucan, Squalane, Allantoin, Bisabolol, Panthenol, Sodium Hyaluronate, Glycerin, Xanthan Gum, Glyceryl Stearate, PEG-100 Stearate, Isoceteth-20, Polysorbate 20, Butylene Glycol, Carbomer, Phenoxyethanol, Methylparaben, Propylparaben, Butylparaben, Isobutylparaben, Ethylparaben, Tetrasodium EDTA, Ethoxydiglycol.",
                procedure: ["Apply twice daily to face, neck and décolleté."],
                reviews: 5,
                gender: "mens",
                type: "oily"
            },
            {
                id: "mo10",
                main_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11291588-1404869687797262.jpg",
                hover_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11291588-2124875114973299.jpg",
                title: "Replenix Age Restore Night Time Therapy",
                bPrice: "95.00",
                aPrice: "65.00",
                desc: "This sophisticated, moisture-boosting, decadently rich night cream nourishes dry skin back to optimum health. Combats skin dryness and enhances barrier function overnight with a controlled and powerful delivery system that is designed to attract, hold and distribute moisture through a advanced system of Ceramides, Humectants and Emollients. Infused with Stem Cells derived from apples, peptides and a broad-spectrum antioxidant complex, including Green Tea Polyphenols, Resveratrol and Caffeine, this soothing, paraben-free and hypoallergenic moisturizer helps guard against environmental damage while helping to reduce the appearance of fine lines and wrinkles in mature skin, leaving skin looking supple, firm and collagen-rich. Suitable for sensitive skin and those on retinoid therapies.",
                ingredients: "Purified Water, Cyclopentasiloxane,Sodium PCA, Glycerin, Caprylic/Capric Triglyceride,Polysorbate-60, Cetearyl Alcohol, Yucca Glauca RootExtract, Dimethicone, Cetearyl Glucoside,Polyacrylamide, C13-14 Isoparaffin, Laureth-7,Ceramide NP, Ceramide AP, Ceramide EOP, SodiumHyaluronate, Phytosphingosine, Cholesterol, SodiumLauroyl Lactylate, Camellia Sinensis (Green Tea)Polyphenols, Malus Domestica Fruit Cell CultureExtract, Squalane, Ceramide 2, Tetrapeptide-21,Resveratrol, Bisabolol, Caffeine, Lecithin, GlycerylStearate, PEG-100 Stearate, DimethiconeCrosspolymer, Carbomer, Xanthan Gum,Phenoxyethanol, Sorbic Acid, Caprylyl Glycol,Disodium EDTA, Fragrance.",
                procedure: ["After cleansing the skin, apply to the desired area (face, neck, décolleté) in the evening or as directed by the doctor."],
                reviews: 4,
                gender: "mens",
                type: "oily"
            },
            {
                id: "mo11",
                main_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11289690-1794871029936020.jpg",
                hover_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11289690-1264871029979277.jpg",
                title: "SkinMedica Ultra Sheer Moisturizer (2oz)",
                bPrice: "69.00",
                aPrice: "69.69",
                desc: "This light, oil and fragrance free formula effectively hydrates skin while Vitamins C and E protect against free radical damage.",
                ingredients: "Water/Aqua/Eau, Cetyl Ethylhexanoate, Sorbitan Stearate, Methyl Gluceth-20, Polysorbate 60, Dimethicone, Tetrahexyldecyl Ascorbate, Tocopherol, Tocopheryl Acetate, Panthenol, Sodium Hyaluronate, Cetearyl Alcohol, Ceteareth-20, Aminomethyl Propanol, Carbomer, Disodium EDTA, Phenoxyethanol, Isobutylparaben, Butylparaben, Ethylparaben, Methylparaben, Propylparaben.",
                procedure: ["Apply twice daily to face, neck and decollete.", "As with any skin care product, avoid getting into eyes.", "If contact occurs, rinse eyes thoroughly with water."],
                reviews: 4,
                gender: "mens",
                type: "oily"
            },
            {
                id: "mo12",
                main_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/12004607-1214929129526791.jpg",
                hover_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/12004607-8344929129569625.jpg",
                title: "No7 Lift and Luminate Triple Action Night Cream 1.69oz",
                bPrice: "18.89",
                aPrice: "16.69",
                desc: "Transform the look of your skin while you sleep with No7 Lift and Luminate Triple Action Night Cream, a nourishing night cream supercharged with technology from the brand's clinically proven Triple Action Serum<br>Targeting three key signs of aging, the night cream will help to visibly reduce wrinkles, lift and firm the appearance of skin and promote a more even tone. The multi-tasking moisturizer will deliver visible results from the first morning, and in two weeks, wrinkles appear reduced and skin looks firmer and lifted. Formulated with the brand's unique lightening complex which helps to fade the look of stubborn pigmentation and dark spots for a more even skin tone. After three weeks, Witness rested, more radiant and healthy-looking skin come morning.",
                ingredients: "Aqua (Water), Glycerin, Butyrospermum Parkii (Shea) Butter, Cyclopentasiloxane, Steareth-21, Caprylic/Capric Triglyceride, C12-15 Alkyl Benzoate, Cyclohexasiloxane, Dimethicone, Steareth-2, Glyceryl Stearate, Cetearyl Alcohol, Polyacrylamide, Butylene Glycol, Alcohol Denat., C13-14 Isoparaffin, Phenoxyethanol, Dimethiconol, Caprylyl Glycol, Ascorbyl Glucoside, Laureth-7, Parfum (Fragrance), Propylene Glycol, Sodium Benzoate, Tocopheryl Acetate, Sodium Hyaluronate, Pentylene Glycol, Hibiscus Abelmoschus Extract, Ethylhexylglycerin, Retinyl Palmitate, Phyllanthus Emblica Fruit Extract, Hydrolyzed Rice Protein, Tetrasodium EDTA, Sorbitan Laurate, Panax Ginseng Root Extract, Carbomer, Dipropylene Glycol, Dimethylmethoxy Chromanol, Xanthan Gum, Polysorbate 20, Hydroxyethylcellulose, Acetyl Dipeptide-1 Cetyl Ester, Morus Alba Leaf Extract, Tocopherol, Palmitoyl Tripeptide-1, Palmitoyl Tetrapeptide-7.",
                procedure: ["Use every evening.", "Massage in small upward circles over your face and neck, after applying your Lift and Luminate TRIPLE ACTION Serum."],
                reviews: 4,
                gender: "women",
                type: "oily"
            },
            {
                id: "mo13",
                main_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11289619-1605043613350945.jpg",
                hover_img: "https://static.thcdn.com/images/large/webp//productimg/1600/1600/11289619-1854892771554485.jpg",
                title: "SkinCeuticals Hydrating B5 Hyaluronic Acid Gel Moisturizer 30ml",
                bPrice: "15.99",
                aPrice: "14.99",
                desc: "Achieve a smooth and youthful complexion with the SkinCeuticals Hydrating B5 Gel; a moisturizing serum that replenishes essential nutrients, whilst restoring a natural radiance to the visage.<br>Suitable for all skin types, the gentle yet effective gel formula envelops the face, neck and chest in a veil of long-lasting hydration. The serum is enriched with Vitamin B5 and Hyaluronic Acid, which work in synergy to bind moisture to skin and enhance the benefits of a daily moisturizer.<br>Without clogging pores, the serum offers additional moisture, which leaves skin supple and smooth.",
                ingredients: "Aqua/Water/Eau, Phenoxyethanol, Calcium Pantothenate, Sodium Hyaluronate.",
                procedure: ["Using fingertips, apply 2-3 drops to the entire face, neck, and chest.", "Avoid the eye area.", "If using in the morning, apply after a SkinCeuticals vitamin C antioxidant serum and before a SkinCeuticals sunscreen.", "If using with a retinol at night, apply after retinol application."],
                reviews: 5,
                gender: "men",
                type: "oily"
            },
        ]
    }
}
var giftsArray = [{
    id: "gift",
    img: "https://s1.thcdn.com/productimg/0/300/300/76/10629476-1343912941-393796.jpg",
    title: "Sarah Chapman Overnight Facial 5ml (Worth $37.00)",
    price: "286.75",
    sec_title: "$37 Sarah Chapman Gift",
    desc: "Receive a free Sarah Chapman Overnight Facial 5ml (Worth $37) when you spend $100 or more on the brand. Complimentary gift will be awarded at the cart. Offer valid for a limited time only, while supplies last."
}, ]
var featured = {
    brand_logo: "https://s1.thcdn.com/widgets/121-us/59/original-MicrosoftTeams-image_%2820%29-100559.png",
    product1: {
        img: "https://static.thcdn.com/images/small/webp//productimg/480/480/13556039-8794935277083219.jpg",
        title: "Revision Skincare Gentle Foaming Cleanser 5floz / 150ml.",
        price: "372.00"
    },
    product2: {
        img: "https://static.thcdn.com/images/small/webp//productimg/480/480/12902722-7844915030891827.jpg",
        title: "Revision Skincare Brightening Facial Wash 6.7 fl.oz.",
        price: "341.00"
    }
}